server:
  port: 8082
  servlet:
    context-path: /videoapp
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: mongodpwdVEfwrAYY5ozsz
      database: libraryapp
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
      enabled: true

